seed: 42
max_iters: 120
max_kl_per_step: 0.0005
project_every_step: true

rtp_band: [0.945, 0.955]
hit_band: [0.30, 0.34]

# Example paytable (p, r) — replace with your own
p_init: [0.68, 0.20, 0.09, 0.02, 0.009, 0.001]  # must sum to 1 after normalize
r:      [0,    1,    2,    5,     10,    25  ]
